version: 1
labels:
- label: "master"
  branch: "^hotfix/.*"
- label: "master"
  branch: "^release/.*"
- label: "master"
  branch: "^dev/.*"
- label: "external-dependency"
  branch: "^combined-dependabots/.*"